package com.company;

public class Main {

    public static void main(String[] args) {


        String BLACK = "\033[0;30m";
        String YELLOW = "\033[0;33m";
        String WHITE = "\033[0;37m";
        String Empty_Character = "\u2587";
        String Sqare = "\u2588";
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + YELLOW + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
        System.out.println(WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + BLACK + Sqare + Sqare + Sqare + WHITE + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare + Sqare);
    }
}
